"""
Amendment A-R4 (2026-07-08): build manuscript-ready markdown tables from
existing artefacts + the A-R1/A-R2/A-R3 outputs. No new statistics beyond
what the amendment registers.

Outputs to revision_2026-07-08/tables/:
  T1_experiment_design.md      18-config grid + aliasing disclosure + sim counts
  T2_main_results_18.md        main-text per-config decomposition summary
  T2b_appendix_72subcells.md   72-row appendix table with absolute m_0 + CIs
  T3_blockC_D2.md              dominance/FOSD/U_c per (config, corner) + Wilson
  T4_policy_contest.md         complete 8-policy contest incl. P2/P3/P4 + CIs
  T5_partition_sensitivity.md  A-R1 capacity-share sensitivity
  T6_stats_and_oos.md          A-R2 multiplicity/rho + A-R3 in/out-of-sample
"""
from __future__ import annotations

import json
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[3]
RESULTS = ROOT / "prototype" / "results"
RAW = RESULTS / "raw"
OUTJ = Path(__file__).resolve().parents[1] / "outputs"
TAB = Path(__file__).resolve().parents[2] / "tables"
CORNERS = ["HC_HI", "HC_LI", "LC_HI", "LC_LI"]
POL_ORDER = ["P0_random", "P1_dest_cluster", "P2_cardinality",
             "P3_dir_balanced", "P4_temporal", "P5_phi", "P6_spo_tree",
             "P7_localsearch"]
POL_SHORT = {p: p.split("_")[0] for p in POL_ORDER}


def wilson(k: int, n: int, z: float = 1.959964):
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return c - h, c + h


def w(path: Path, text: str):
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path}")


def main() -> None:
    TAB.mkdir(parents=True, exist_ok=True)
    blockA = json.loads((RESULTS / "v0_5_phase5_blockA.json").read_text(encoding="utf-8"))
    blockB = json.loads((RESULTS / "v0_5_phase5_blockB.json").read_text(encoding="utf-8"))
    blockC = json.loads((RESULTS / "v0_5_phase5_blockC.json").read_text(encoding="utf-8"))
    ar1 = json.loads((OUTJ / "ar1_partition_sensitivity.json").read_text(encoding="utf-8"))
    ar2 = json.loads((OUTJ / "ar2_stats_hardening.json").read_text(encoding="utf-8"))
    ar3 = json.loads((OUTJ / "ar3_oos_corner_selection.json").read_text(encoding="utf-8"))
    dfA = pd.read_csv(RAW / "mvs_v0_5_phase5_blockA.csv")

    # ---------------- T1: experiment design ---------------------------------
    grid = (dfA[["config_id", "F", "n_amrs", "n_elevators", "demand"]]
            .drop_duplicates().sort_values("config_id"))
    nB = len(pd.read_csv(RAW / "mvs_v0_5_phase5_blockB.csv"))
    nC = len(pd.read_csv(RAW / "mvs_v0_5_phase5_blockC.csv"))
    nA = len(dfA)
    nP7 = len(pd.read_csv(RAW / "mvs_v0_5_phase5_ablation_P7.csv"))
    nSch = len(pd.read_csv(RAW / "mvs_v0_5_phase5_ablation_scheme.csv"))
    lines = [
        "# Table 1. Experimental design (publication scale, Phase 5)",
        "",
        "Full factorial would be F in {3,5,8} x |A| in {5,10,20} x E in {1,2} "
        "x demand in {uniform, clustered, diurnal} (54 configs). The study "
        "uses an 18-config one-third fraction generated by the defining "
        "relation `demand_idx = (F_idx + |A|_idx) mod 3`, crossed with both "
        "E levels.",
        "",
        "**Aliasing disclosure.** Under this fraction the main effects of F, "
        "|A|, and demand are aliased: no clean main effect of any of the "
        "three is identifiable from this grid. Marginal displays over F or "
        "|A| are therefore descriptive only; per-demand facets are the "
        "pre-registered presentation.",
        "",
        "| config | F (floors) | \\|A\\| (AMRs) | E (elevators) | demand |",
        "|---:|---:|---:|---:|---|",
    ]
    for _, r in grid.iterrows():
        lines.append(f"| {r.config_id} | {r.F} | {r.n_amrs} | "
                     f"{r.n_elevators} | {r.demand} |")
    lines += [
        "",
        "| Block | Contents | Simulations |",
        "|---|---|---:|",
        f"| A (decomposition, H-D1) | 18 configs x {{M1, M2}} x sizes {{8, 30}} "
        f"x 5 arms (4 corners + random) x 200 waves | {nA:,} |",
        f"| B (wave-release policy contest, H-Policy) | 6 configs x sizes "
        f"{{8, 30}} x P0-P6 x 200 released waves | {nB:,} |",
        f"| C (model chain, H-D2/H-D3) | 6 configs x 5 arms x matched waves "
        f"x {{M1, M2, M3}} | {nC:,} |",
        f"| **Pre-registered core total** | | **{nA + nB + nC:,}** |",
        f"| Amendment 9.1: P7 local search | 12 cells x 200 | {nP7:,} |",
        f"| Amendment 9.1: partition schemes (A4) | 6 configs x "
        f"{{2x2, 3x3, 2x2x2}} + random arms | {nSch:,} |",
        "",
        "Elevator capacity c = 2 throughout the core grid (the supplementary "
        "capacity sweep covers c in {2,3,4,5}). Dispatch rule (operational "
        "stage) held fixed. All wave-release policies draw from one shared "
        "candidate pool per cell.",
    ]
    w(TAB / "T1_experiment_design.md", "\n".join(lines) + "\n")

    # ---------------- T2 / T2b: main results --------------------------------
    # absolute m0 per sub-cell from raw
    m0_abs = {}
    for (cid, model, size), g in dfA.groupby(["config_id", "model", "size"]):
        m0_abs[(int(cid), model, int(size))] = float(
            np.median(g[g["arm"] == "random"]["makespan"]))

    per = blockA["per_subcell"]
    # main text: aggregate over the 4 sub-cells per config
    lines = [
        "# Table 2. Bound-and-Gap decomposition by configuration "
        "(publication scale)",
        "",
        "Per config: mean over the four sub-cells (models {M1, M2} x wave "
        "sizes {8, 30}) of the pool-relative quantities; m_0 range is the "
        "absolute median makespan of the random arm (time units). `resolved` "
        "counts sub-cells whose pre-registered 95% bootstrap CI on GAP "
        "excludes 0 (gate D1-d). Full 72-row version: Table 2b (appendix).",
        "",
        "| config | F | \\|A\\| | E | demand | m_0 range | GAP | H_up | M_Phi "
        "| capacity share | resolved |",
        "|---:|---:|---:|---:|---|---|---:|---:|---:|---:|---:|",
    ]
    for cid in sorted({r["config_id"] for r in per}):
        sub = [r for r in per if r["config_id"] == cid]
        m0s = [m0_abs[(cid, r["model"], r["size"])] for r in sub]
        gap = np.mean([r["GAP"] for r in sub])
        hup = np.mean([r["H_up"] for r in sub])
        mphi = np.mean([r["M_Phi"] for r in sub])
        res = sum(r["d1d"] for r in sub)
        share = hup / gap if gap else float("nan")
        s0 = sub[0]
        lines.append(
            f"| {cid} | {s0['F']} | {s0['n_amrs']} | {s0['n_elevators']} | "
            f"{s0['demand']} | {min(m0s):.0f}-{max(m0s):.0f} | {gap:.3f} | "
            f"{hup:.3f} | {mphi:.3f} | {share:.2f} | {res}/4 |")
    mean_gap = blockA["mean_GAP"]
    mH = np.mean([r["H_up"] for r in per]); mM = np.mean([r["M_Phi"] for r in per])
    lines += [
        "",
        f"Grid means (72 sub-cells): GAP {mean_gap:.4f}, H_up {mH:.4f}, "
        f"M_Phi {mM:.4f}; Phi-rule capacity share of mean GAP "
        f"{mH/(mH+mM):.3f}. The capacity share is partition-conditional "
        "(2x2 quartile corners) and pool-relative; see the "
        "partition-sensitivity analysis (Table 5) before quoting it as a "
        "headline.",
    ]
    w(TAB / "T2_main_results_18.md", "\n".join(lines) + "\n")

    lines = [
        "# Table 2b (appendix). Bound-and-Gap decomposition, all 72 sub-cells",
        "",
        "m_0 = absolute median makespan of the random arm (time units); GAP, "
        "H_up, M_Phi pool-relative; CI = pre-registered 95% bootstrap CI on "
        "GAP; `res` = D1-d resolved.",
        "",
        "| config | demand | model | size | m_0 | GAP | H_up | M_Phi | "
        "GAP 95% CI | res |",
        "|---:|---|---|---:|---:|---:|---:|---:|---|:--:|",
    ]
    for r in sorted(per, key=lambda r: (r["config_id"], r["model"], r["size"])):
        m0 = m0_abs[(r["config_id"], r["model"], r["size"])]
        model = "M1" if r["model"] == "abstraction" else "M2"
        lines.append(
            f"| {r['config_id']} | {r['demand']} | {model} | {r['size']} | "
            f"{m0:.0f} | {r['GAP']:.3f} | {r['H_up']:.3f} | {r['M_Phi']:.3f} | "
            f"[{r['gap_ci_lo']:.3f}, {r['gap_ci_hi']:.3f}] | "
            f"{'y' if r['d1d'] else 'n'} |")
    lines += ["", f"Resolved: {sum(r['d1d'] for r in per)}/72 (pre-registered "
              "gate D1-d, PARTIAL: bar was 58). Two sub-cells show "
              "H_up slightly below 0 (truncated quartile corners are "
              "non-covering; finite-sample effect, see section 4.1.1).",]
    w(TAB / "T2b_appendix_72subcells.md", "\n".join(lines) + "\n")

    # ---------------- T3: Block C D2 table ----------------------------------
    d2 = blockC["H_D2"]
    wil = {(c["config_id"], c["corner"]): c
           for c in ar2["blockC_dominance_wilson"]["per_cell"]}
    lines = [
        "# Table 3. Hedge Rule empirical foundation (Block C, publication "
        "scale)",
        "",
        "Per (config, corner): per-wave dominance frequency P(M2 >= M1) with "
        "Wilson 95% CI (amendment A-R2), FOSD quantile-coupling check, and "
        "the one-sided bound U_c(0.05) relative to the cell's random-arm "
        "median m_0.",
        "",
        "| config | corner | P(M2 >= M1) | Wilson 95% CI | FOSD | U_c(0.05) "
        "| U_c / m_0 |",
        "|---:|---|---:|---|:--:|---:|---:|",
    ]
    for c in d2["per_cell"]:
        wc = wil[(c["config_id"], c["corner"])]
        lines.append(
            f"| {c['config_id']} | {c['corner']} | {c['perwave_dom']:.3f} | "
            f"[{wc['wilson_lo']:.3f}, {wc['wilson_hi']:.3f}] | "
            f"{'y' if c['fosd_ok'] else 'n'} | {c['U_c_005']:.1f} | "
            f"{c['U_c_005']/c['m0']*100:.1f}% |")
    pool = ar2["blockC_dominance_wilson"]["pooled"]
    lines += [
        "",
        f"Pooled dominance {pool['k']}/{pool['n']} = {pool['dom_frac']:.4f}, "
        f"Wilson 95% CI [{pool['wilson_lo']:.4f}, {pool['wilson_hi']:.4f}]. "
        f"DRO agreement (D2-d): {d2['n_collapse']}/{d2['n_configs']} configs. "
        "All gates cleared (H-D2 PASS). Scope: the six-configuration "
        "model-chain block, c = 2.",
    ]
    w(TAB / "T3_blockC_D2.md", "\n".join(lines) + "\n")

    # ---------------- T4: complete policy contest ---------------------------
    cellsB = blockB["per_cell"]
    n_cells = len(cellsB)
    mm = blockB["mean_median_makespan"]

    def wins(i, j):
        wi = sum(c[i] < c[j] for c in cellsB)
        wj = sum(c[j] < c[i] for c in cellsB)
        return wi, wj, n_cells - wi - wj

    lines = [
        "# Table 4. Complete wave-release policy contest (Block B, "
        "publication scale)",
        "",
        "All seven pre-registered comparators plus the P7 local-search "
        "reference, over the 12 (config, size) cells. Win fractions use "
        "strict inequality of cell-median makespans; ties shown separately. "
        "Wilson 95% CIs from amendment A-R2 (n = 12, so intervals are wide; "
        "reported as such).",
        "",
        "## 4a. Grand mean of cell-median makespans (time units)",
        "",
        "| policy | description | grand mean |",
        "|---|---|---:|",
    ]
    desc = {"P0_random": "random selection (naive baseline)",
            "P1_dest_cluster": "destination-clustered (practitioner heuristic)",
            "P2_cardinality": "cardinality-only (fewest cross-floor orders)",
            "P3_dir_balanced": "direction-balanced",
            "P4_temporal": "temporal-clustered",
            "P5_phi": "Phi corner rule (cell-median, the diagnostic policy)",
            "P6_spo_tree": "SPO-Tree cell-mean predictor",
            "P7_localsearch": "40-iteration local search (reference optimum)"}
    for p in POL_ORDER:
        lines.append(f"| {POL_SHORT[p]} | {desc[p]} | {mm[p]:.1f} |")
    lines += [
        "",
        "## 4b. Pairwise wins over 12 cells (row beats column / ties)",
        "",
        "| | " + " | ".join(POL_SHORT[p] for p in POL_ORDER) + " |",
        "|---|" + "---|" * len(POL_ORDER),
    ]
    for i in POL_ORDER:
        row = [f"**{POL_SHORT[i]}**"]
        for j in POL_ORDER:
            if i == j:
                row.append("-")
            else:
                wi, wj, t = wins(i, j)
                row.append(f"{wi}" + (f" (t{t})" if t else ""))
        lines.append("| " + " | ".join(row) + " |")
    lines += [
        "",
        "## 4c. Key comparisons with uncertainty",
        "",
        "| comparison | wins / n | win frac | Wilson 95% CI |",
        "|---|---:|---:|---|",
    ]
    for i, j in [("P5_phi", "P0_random"), ("P5_phi", "P1_dest_cluster"),
                 ("P5_phi", "P6_spo_tree"), ("P5_phi", "P7_localsearch"),
                 ("P2_cardinality", "P5_phi")]:
        wi, wj, t = wins(i, j)
        lo, hi = wilson(wi, n_cells)
        lines.append(f"| {POL_SHORT[i]} beats {POL_SHORT[j]} | {wi}/{n_cells} "
                     f"| {wi/n_cells:.2f} | [{lo:.2f}, {hi:.2f}] |")
    p2w, p5w, _ = wins("P2_cardinality", "P5_phi")
    lines += [
        "",
        f"P5 sits {100*blockB['P5_above_P7_frac']:.1f}% above the P7 "
        "local-search reference on average and never beats it. "
        f"The cardinality-only heuristic P2 beats P5 in {p2w}/{n_cells} cells "
        f"and posts a lower grand mean ({mm['P2_cardinality']:.1f} vs "
        f"{mm['P5_phi']:.1f}): low cross-floor count is itself a strong "
        "lever, consistent with the capacity-side diagnosis. P5's value is "
        "diagnostic (simulation-free, interpretable), not a performance "
        "champion; this is the pre-registered framing.",
    ]
    w(TAB / "T4_policy_contest.md", "\n".join(lines) + "\n")

    # ---------------- T5: partition sensitivity -----------------------------
    rows = ar1["per_config_scheme"]
    lines = [
        "# Table 5. Partition-sensitivity of the capacity share "
        "(amendment A-R1, reanalysis of stored A4 data)",
        "",
        "Six configs, wave size 16, model M2. Two share metrics: the "
        "partition-intrinsic `H_up/UB` (oracle-slack denominator, defined "
        "for every scheme) and, for reference, the Phi-rule share "
        "`H_up/(H_up+M_Phi)` from the 72-sub-cell Block A grid (defined "
        "only for the 2x2 scheme, sizes {8,30}, models {M1,M2}).",
        "",
        "| config | scheme | H_up | oracle slack | capacity share H_up/UB | "
        "95% CI |",
        "|---:|---|---:|---:|---:|---|",
    ]
    for r in sorted(rows, key=lambda r: (r["scheme"], r["config_id"])):
        lines.append(f"| {r['config_id']} | {r['scheme']} | {r['H_up']:.3f} | "
                     f"{r['S_oracle']:.3f} | {r['capacity_share']:.2f} | "
                     f"[{r['cap_ci_lo']:.2f}, {r['cap_ci_hi']:.2f}] |")
    dr = ar1["decision_rule"]
    lines += [
        "",
        "| scheme | configs with capacity share > 0.5 | locked rule "
        "(>= 5/6) |",
        "|---|---:|---|",
    ]
    for s, v in dr.items():
        lines.append(f"| {s} | {v['n_capacity_dominant']}/{v['n_configs']} | "
                     f"{'meets' if v['meets_5_of_6'] else 'FAILS'} |")
    lines += [
        "",
        "**Outcome (locked rule fired).** Under the oracle-slack metric the "
        "capacity-dominant reading is NOT scheme-stable (2x2: 2/6; 3x3: 4/6; "
        "2x2x2 with T: 5/6). The manuscript therefore states capacity-side "
        "dominance as a partition- and metric-conditional finding: it holds "
        "for the Phi-rule share on the 72-sub-cell grid "
        f"({ar1['blockA_reference']['phi_rule_capacity_share_of_mean_GAP']:.2f} "
        "of mean GAP) and must not be quoted as a universal property. "
        "Terciles require new simulation (amendment B-6).",
    ]
    w(TAB / "T5_partition_sensitivity.md", "\n".join(lines) + "\n")

    # ---------------- T6: stats hardening + OOS -----------------------------
    d1d = ar2["d1d_multiplicity"]
    rho = ar2["hd3_rho"]
    lines = [
        "# Table 6. Statistical hardening and out-of-sample checks "
        "(amendments A-R2, A-R3)",
        "",
        "| item | pre-registered artefact | amendment result | reading |",
        "|---|---|---|---|",
        f"| D1-d resolved sub-cells | 57/72 (PARTIAL, gate not re-judged) | "
        f"BH-FDR(q=0.05): {d1d['n_resolved_BH05']}/72 | the one-cell miss is "
        "not a multiplicity artefact; under FDR control MORE cells resolve |",
        f"| H-D3 mean corner-ranking Spearman rho | 0.75 (point) | 95% "
        f"bootstrap CI [{rho['ci_lo']:.2f}, {rho['ci_hi']:.2f}] | "
        "model-sensitive branch confirmed with uncertainty attached |",
        f"| Block C pooled dominance | 99.2% | Wilson 95% CI "
        f"[{ar2['blockC_dominance_wilson']['pooled']['wilson_lo']*100:.1f}%, "
        f"{ar2['blockC_dominance_wilson']['pooled']['wilson_hi']*100:.1f}%] | "
        "chain-dominance frequency tightly estimated |",
        f"| Block B distribution tests | none | "
        f"{ar2['blockB_mannwhitney_BH']['n_significant']}/"
        f"{ar2['blockB_mannwhitney_BH']['n_tests']} Mann-Whitney tests "
        "significant after BH(0.05) | policy differences are real at the "
        "per-cell distribution level |",
        f"| M_Phi winner's-curse check | in-sample mean "
        f"{ar3['mean_M_Phi_in']:.4f} | out-of-sample mean "
        f"{ar3['mean_M_Phi_oos']:.4f} (shrink "
        f"{100*ar3['rel_shrink_M_Phi']:.1f}%, below the locked 25% "
        "materiality bar) | in-sample M_Phi mildly optimistic; conclusions "
        "unchanged |",
        f"| H_up out-of-sample | in-sample mean {ar3['mean_H_up_in']:.4f} | "
        f"OOS mean {ar3['mean_H_up_oos']:.4f} (shrink "
        f"{100*ar3['rel_shrink_H_up']:.1f}%) | capacity share stable: "
        f"{ar3['capacity_share_in']:.3f} in-sample vs "
        f"{ar3['capacity_share_oos']:.3f} OOS |",
        "",
        f"Corner-selection stability (A-R3): train argmin != test argmin in "
        f"{ar3['n_qmin_train_neq_test']}/72 sub-cells; M_Phi_oos < 0 in "
        f"{ar3['n_M_Phi_oos_negative']}/72 (winner's-curse correction where "
        "the corner landscape is flat).",
    ]
    w(TAB / "T6_stats_and_oos.md", "\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
